#数据源配置
datasource:
    druid:
        name: test
        url: jdbc:mysql://localhost:3306/pay?useUnicode=true&amp;characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: 1234
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#数据源配置
flyway:
    baseline-description: zero
    baseline-version: 1
    baseline-on-migrate: true
    check-location: false
    clean-on-validation-error: true
    enabled: true
    encoding: UTF-8
    ignore-failed-future-migration: false
#    init-sqls:
    locations: classpath:resources/db/sql/
    out-of-order: false
    password: 1234
#    placeholder-prefix:
#    placeholder-replacement:
#    placeholder-suffix:
#    placeholders.*:
    schemas: pay
    sql-migration-prefix: pay
    sql-migration-separator: __
    sql-migration-suffix: .sql
#    table:
    url: jdbc:mysql://localhost:3306/pay?useUnicode=true&amp;characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    user: root
    validate-on-migrate: true
#eureka client配置
spring:
  application:
    name: easy-ssm-core
#指定服务端口
server:
  port: 2222
#指定服务中心位置
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/