#服务端口
server:
  port: 1001
#eureka相关配置
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false